// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxA8BsPDJQVYqWMiFnukLLIgoaz8QFQME',
    appId: '1:490033109654:android:3611b8d2f4ecafd5df40b7',
    messagingSenderId: '490033109654',
    projectId: 'songgpt-cefda',
    storageBucket: 'songgpt-cefda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0nJ_PNchaDIOzzuQN8UAeDC1h_7MNTNo',
    appId: '1:490033109654:ios:2b0dd8957e0efb07df40b7',
    messagingSenderId: '490033109654',
    projectId: 'songgpt-cefda',
    storageBucket: 'songgpt-cefda.appspot.com',
    androidClientId: '490033109654-1kbs81rmucaql4j0rgjim1eura2u43p1.apps.googleusercontent.com',
    iosClientId: '490033109654-dsbcbib91ea7aspmv8gbooqeicumoq73.apps.googleusercontent.com',
    iosBundleId: 'com.bitwisedhruv.songgpt',
  );

}